name: Pytest 🧪

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.9','3.12']
        os: [windows-latest]
    timeout-minutes: 30
    env:
      # Display must be available globally for linux to know where xvfb is
      DISPLAY: ":99.0"
      QT_SELECT: "qt6"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        # prerequisites
        python -m pip install --upgrade pip wheel
        python -m pip install coverage flake8 pytest pytest-qt
    - name: Install package
      run: |
        pip install .
    - name: List installed packages
      run: |
        pip freeze
    - name: Test with pytest
      run: |
        coverage run --source=firepydaq --omit=*NIConfig*,*app*,*Echo*,*NISYS* -m pytest -x tests
    - name: Generate Coverage Report  
      run: |
        coverage report -m
    # Can be added later once the code and documentation is resolved. 
    # - name: Lint with flake8
    #   run: |
    #     flake8 --exclude _version.py .
