name: Render Sphinx docs 📖

on: 
  push:
  pull_request:

jobs:
  build:
    if: ${{ contains(github.event.head_commit.message, 'update docs') }}
    if: ${{ github.repository_owner == 'ulfsri' }}
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]
    steps:
    - name: Set env
      shell: bash
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        cd docs
        ls
        pip install -r requirements.txt
        cd ..
    - name: Build HTML
      run: |
        sphinx-build docs _build
      # uses: ammaraskar/sphinx-action@0.4
      # with:
      #   docs-folder: "docs/"
    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: html-docs
    #     path: docs/_build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/
        force_orphan: true
        publish_branch: firepydaq-pages
